<?php
/**
 * @file
 * ec_mapeditor_target.module file.
 */

/**
 * Implements hook_layer_info().
 *
 * Registers the name of the map layer sub module and which custom form
 * elements it wants to add to the map layer forms. CSV layer has no custom
 * fields.
 */
function ec_mapeditor_target_layer_info() {
  return array(
    'target_layer' => array(
      'form_elements' => array('popup', 'clustering', 'icon', 'attribution'),
      'custom_js' => base_path() . drupal_get_path('module', 'ec_mapeditor_target') . "/js/target_layer.js?v=" . rand(0, 33333),
    ),
  );
}

/**
 * Implements hook_layer_content_alter().
 *
 * See MapLayerController->buildContent();
 */
function ec_mapeditor_target_layer_content_alter(&$content, $wrapper, $entity) {
  // Fetches map data from country layer.
  if ($entity->type == 'target_layer') {
    $settings = drupal_json_decode($wrapper->settings->value());

    $layers[] = array(
      'layer_settings' => $settings,
      'label' => $wrapper->title->value(),
      'countries' => 'county test',
      'id' => _ec_mapeditor_layer_id($wrapper->title->value()),
    );
    $content['#attached']['js'][] = array(
      'data' => array(
        'target_layers' => $layers,
      ),
      'type' => 'setting',
    );
    return $content;
  }
}

/**
 * Implements hook_layer_form_alter().
 */
function ec_mapeditor_target_layer_form_alter(&$form, $settings, $type) {
  if ($type == 'target_layer') {
    $url = file_create_url(drupal_get_path('module', 'ec_mapeditor_target') . '/template.txt');
    $form['map_target_countries'][LANGUAGE_NONE][0]['value']['#description'] .= ' ' . t('<a href="!url">Example</a>', array('!url' => $url));
    return $form;
  }
}